### ISSUE TITLE
Camera going through the rotatting table

### ISSUE THREAD

**Issue by MashdorDev** [MashdorDev/unbreaded#138]
Move the Camera to a position that the player can see while going through the rotating table.

**Comment by MashdorDev** [comment]
A possible solution for this - 

https://forums.unrealengine.com/t/properly-hide-parts-of-objects-between-camera-and-character/501612

https://www.unrealengine.com/marketplace/en-US/product/fade-camera-occluders

**Comment by MashdorDev** [comment]
Pushed to Beta

**Comment by antoniukoff** [comment]
https://alfredbaudisch.com/blog/gamedev/unreal-engine-ue/unreal-engine-actors-transparent-block-camera-occlusion-see-through/
