### ISSUE TITLE
EXCEPTION_ACCESS_VIOLATION

### ISSUE THREAD

**Issue by MashdorDev** [MashdorDev/unbreaded#201]
```
Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x0000000041c00038

UnrealEditor_CoreUObject
UnrealEditor_Engine
UnrealEditor_unbread!ASCharacter::Tick() [D:\Dor\Projects\unbread\Source\unbread\Private\SCharacter.cpp:347]

```

The error happened when I went to the sink, detached from the body, and then couldn't regenerate the body on a new pile so I went back to the old pile and the game crashed.

it seems to be related to how many times you do it or you try to regenerate on the old pile many times or a few times

**Comment by MashdorDev** [comment]
I was able to catch it in a recording 

https://github.com/MashdorDev/unbreaded/assets/56084381/7867998d-d10a-4498-95b3-14a652261bff

**Comment by antoniukoff** [comment]
@MashdorDev  fixed

**Comment by MashdorDev** [comment]
Awesome, so please pull this change as soon as possible so I can repack it and upload it as the alpha
