### ISSUE TITLE
Graphics settings customization

### ISSUE THREAD

**Issue by rylerbleau** [MashdorDev/unbreaded#286]
Everything except foliage
![image](https://github.com/MashdorDev/unbreaded/assets/73083256/f09eb3fe-51f5-4134-8dfe-d7414e41f37d)

**Comment by GageM** [comment]
![Screenshot (22)](https://github.com/MashdorDev/unbreaded/assets/56518920/c970782d-bf85-4ca0-8546-d36963f385be)
![Screenshot (24)](https://github.com/MashdorDev/unbreaded/assets/56518920/1daf6413-d4fc-4570-8be1-f3747cd783dc)
